### ISSUE TITLE
Package sounds into extension

### ISSUE THREAD

**Issue by mkpaz** [armonge/gnome-shell-extension-focusli#10]
Could you please package basic sounds into extension itself (not to download them)? Unfortunately I can't directly connect to soundbible.com (only through proxy). Corresponding IP not pinging. I don't know whether this caused network provider problem or just the permanent ban of ip adresses of my country. It will be great not to rely on third-party services. At least for basic features.

PS. Also please consider idea to show some sort of error message if sound files can't be downloaded. It looks weird when all works but silent.

**Comment by felipeborges** [comment]
Hi, I am sorry to hear that. I will definitely support your case in the following update.

Thanks a lot for your interest in the extension and for filling this issue here as well.

**Comment by diazbastian** [comment]
If the audio clips will be packed with the extension, would it be convenient to change its format to vorbis or opus?
Commonly the necessary software is not installed by default and an ordinary user will think the extension is broken.

**Comment by felipeborges** [comment]
@diazbastian yes, this has been taken into consideration as well.

**Comment by da2x** [comment]
When I downloaded the audio clips, two of the clips got corrupted and I had to figure out how to reset the extension to clean out the broken files. Bundling the sound files would solve my problem as well.

**Comment by armonge** [comment]
Fixed in https://github.com/armonge/gnome-shell-extension-focusli/commit/a0b3b7f5015959578165ea90a98dfb083861344f
