### ISSUE TITLE
playback stops automatically after a about 10 seconds

### ISSUE THREAD

**Issue by ge0rgecz** [armonge/gnome-shell-extension-focusli#12]
the playback stops automatically after a about 10 seconds. I've distro upgraded recently from 16.04 to 17.04 and my GNOME Shell is also up to 3.24.1

**Comment by ghost** [comment]
Same here on Fedora 25, Gnome 3.22

It makes the extension kind of useless. But very promising if it can be fixed.

**Comment by christiangun** [comment]
I have this problem as well on a fresh Ubuntu 17.04 install using Gnome Shell 3.24.1. I can add that after a few seconds after it stopped it resumes playing again, only to stop and restart infinitely.

**Comment by jdtanner** [comment]
Ditto; same problem here with a fresh install of 17.04.

Awesome extension otherwise!

**Comment by dimitrov-adrian** [comment]
+1

**Comment by udaycoder** [comment]
Same here on fedora 26 gnome

**Comment by dennisotugo** [comment]
Same here on rhel 7

**Comment by zagortenay333** [comment]
You need to set prerolled to false in the stop method, or use PAUSED instead of NULL state.

For those who wanna fix it themselves:

Change this:
https://github.com/felipeborges/gnome-shell-extension-focusli/blob/d8fb63401204a145e3d237300338a32ce5358f28/sound.js#L111-L113

To this:
```javascript
pause: function() {
    this.playbin.set_state(Gst.State.NULL);
    this.prerolled = false;
}
```
