### ISSUE TITLE
Can't reach _www.soundbible.com_!!!

### ISSUE THREAD

**Issue by konkor** [armonge/gnome-shell-extension-focusli#13]
I think **www.soundbible.com** is not available worldwide...
```
$ ping www.soundbible.com
ping: unknown host www.soundbible.com
$
```
-----
I have downloaded the sounds through the USA proxy only.

**Comment by konkor** [comment]
here is free sounds library https://www.freesound.org/browse/tags/nature/

**Comment by felipeborges** [comment]
Hi, thanks for your report. In the next release we will ship some files within the extension and also allow the creation of custom ones through the UI.
