### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by felipeborges** [armonge/gnome-shell-extension-focusli#19]
I'm no longer interested on maintaining this extension, but it seems a bit popular still. So if you are interested on taking over, please reply here so I could transfer it to you.

**Comment by armonge** [comment]
Hi @felipeborges, i don't really have much experience with maintaining an extension, but if you are interested in doing some initial mentoring i'd love to get started with this one. I already made a PR  so the extension can support gnome 3.3.2

**Comment by felipeborges** [comment]
Thanks for your interest! 

I deactivated the extension under my user account https://extensions.gnome.org/extension/1224/focusli/

So I can transfer this repository to your github account and you can upload under your account to extensions.gnome.org once you make a release. Sounds good?

**Comment by armonge** [comment]
Hi! Sounds good, i just uploaded the extension to https://extensions.gnome.org/extension/1726/focusli/ seems like it's under review for now

**Comment by felipeborges** [comment]
Great. You will need to delete or rename your fork so I can transfer this repository into your account.

**Comment by armonge** [comment]
Hi! I just renamed it, i think that should work. Also, sent you a message over twitter, seems like it's easier to just chat instead of using an issue comment section for this

**Comment by felipeborges** [comment]
Alright, so it is now officially under your watch. Take care of it and @mention me if you need any help.
