### ISSUE TITLE
Can't add icons

### ISSUE THREAD

**Issue by SubatomicCat** [armonge/gnome-shell-extension-focusli#25]
I am unable to add icons to custom sounds by inserting a local path to a file on my computer in the "database.json" file. No icon shows up when I try this approach.

GNOME Shell 3.30.2
Zorin OS 15.2

**Comment by armonge** [comment]
Hi SubatomicCat, could you please share your database.json file?

**Comment by armonge** [comment]
@SubatomicCat could you please share your database.json file?

**Comment by SubatomicCat** [comment]
Here it is. Have tried both PNG and SVG formats.

{
  "sounds": [
    {
      "name": "Light Rain",
      "uri": "/home/user/Documents/projects/focusli/songs/final/light_rain.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/cloud-rain.png"
    },
    {
      "name": "Heavy Rain",
      "uri": "/home/user/Documents/projects/focusli/songs/final/heavy_rain.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/clouds-thunder.png"
    },
    {
      "name": "Ocean",
      "uri": "/home/user/Documents/projects/focusli/songs/final/ocean_waves.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/ocean-wave.png"
    },
    {
      "name": "River",
      "uri": "/home/user/Documents/projects/focusli/songs/final/river_waterfall.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/river.svg"
    },
    {
      "name": "Wind",
      "uri": "/home/user/Documents/projects/focusli/songs/final/wind.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/wind.svg"
    },
    {
      "name": "Nature Sounds",
      "uri": "/home/user/Documents/projects/focusli/songs/final/nature_sounds.m4a",
      "icon": "/home/user/Documents/projects/focusli/icons/forest.svg"
    }
    {
      "name": "Coffee House",
      "uri": "/home/user/Documents/projects/focusli/songs/final/coffee.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/coffee.svg"
    }
    {
      "name": "Bonfire",
      "uri": "/home/user/Documents/projects/focusli/songs/final/bonfire.m4a",
      "icon": "/home/user/Documents/projects/focusli/icons/fire.svg"
    }
  ]
}

**Comment by SubatomicCat** [comment]
Forgot to say that I take out the last two entries in the database to avoid issue #24

**Comment by armonge** [comment]
@SubatomicCat i've just made a new version that should allow for arbitrary icons using png and svg. That being said, there's an error in your JSON. It should be like:


```
{
  "sounds": [
    {
      "name": "Light Rain",
      "uri": "/home/user/Documents/projects/focusli/songs/final/light_rain.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/cloud-rain.png"
    },
    {
      "name": "Heavy Rain",
      "uri": "/home/user/Documents/projects/focusli/songs/final/heavy_rain.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/clouds-thunder.png"
    },
    {
      "name": "Ocean",
      "uri": "/home/user/Documents/projects/focusli/songs/final/ocean_waves.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/ocean-wave.png"
    },
    {
      "name": "River",
      "uri": "/home/user/Documents/projects/focusli/songs/final/river_waterfall.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/river.svg"
    },
    {
      "name": "Wind",
      "uri": "/home/user/Documents/projects/focusli/songs/final/wind.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/wind.svg"
    },
    {
      "name": "Nature Sounds",
      "uri": "/home/user/Documents/projects/focusli/songs/final/nature_sounds.m4a",
      "icon": "/home/user/Documents/projects/focusli/icons/forest.svg"
    },
    {
      "name": "Coffee House",
      "uri": "/home/user/Documents/projects/focusli/songs/final/coffee.mp3",
      "icon": "/home/user/Documents/projects/focusli/icons/coffee.svg"
    },
    {
      "name": "Bonfire",
      "uri": "/home/user/Documents/projects/focusli/songs/final/bonfire.m4a",
      "icon": "/home/user/Documents/projects/focusli/icons/fire.svg"
    }
  ]
}
```

**Comment by SubatomicCat** [comment]
Amazing man, how do I download it? Don't see any updates in extensions.gnome.org or the project releases.
And weird there was an error in the JSON file, I used the original as the base. But oh well, will look into that. 
Thanks!

**Comment by armonge** [comment]
@SubatomicCat it's still on review on the gnome shell extensions website. Should be live soon

**Comment by armonge** [comment]
@SubatomicCat version 5 is now live

**Comment by SubatomicCat** [comment]
Thanks man, but now I can't install version 5. Opened a new issue, as it seems to be different from issues #26 and #27
