### ISSUE TITLE
Error on Installation 

### ISSUE THREAD

**Issue by rtlewis88** [armonge/gnome-shell-extension-focusli#26]
I upgraded (a complete reinstall) to openSUSE Leap 15.2, which uses 3.34. I have successfully used focusli with no prob for a few years, but now, trying all the ways I know to install (including manual) focusli presents this installation error.
Thanks in advance!

**Comment by armonge** [comment]
Hi @rtlewis88 ! which installation error are you getting?

**Comment by rtlewis88** [comment]
Whether or not I try to install manually, or via the reg way (vis-a-vis the GS-Extension page), I simply get the "Error" emblem when either on the extension page, during the installation attempt - or after I go to the "Installed Extensions" page (and GNOME Tweaks too), and see "Error" next to the focusli, extension listing. In other words, the system is rejecting all attempts my to get the directory to activate, and stay in the .local/share/gnome-shell directory. Could I be missing some dependency, since the new install. It was a standard, full install of GNOME, though something's nevertheless amiss with it - and I need my focusli. Thanks, again.

**Comment by armonge** [comment]
Could you try getting the error message by typing `Alt+r` and then `lg` 

It should show [Gnome's Looking Glass](https://wiki.gnome.org/Projects/GnomeShell/LookingGlass), you can then click on "Extensions" and there you can get the message

**Comment by rtlewis88** [comment]
Hi, I ended up reinstalling my OS, and then focusli installed correctly. Thanks for the extension, and sorry for the drama!
