### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by roumano** [armonge/gnome-shell-extension-focusli#7]
Hi,

it's failed to install the extension :  
on "https://extensions.gnome.org/extension/1224/focusli/" if i click on on, it's ask to install then say "on"
but if i refresh the page, it's say not install ...

reading the documentation ( https://wiki.gnome.org/Projects/GnomeShell/Extensions ) didn't help me to understand what it's the issue
```
Debugging extensions

On systemd-based systems (like Debian), you can see error and log output of extensions using journalctl /usr/bin/gnome-session -f. On other systems, logs might be written to ~/.xsession-errors.

You can log messages from an extension into this log for informational or debugging purposes using log(msg). 
```

In my log i only have the install but don't see any error

mai 17 14:36:03 pc41.aws.edifixio.com gnome-software-service.desktop[2148]: 12:36:03:0730 Gs  no app for changed focusli@feborg.es
mai 17 14:36:03 pc41.aws.edifixio.com org.gnome.Shell.desktop[1944]:  extracting: /home/fedora/.local/share/gnome-shell/extensions/focusli@feborg.es/metadata.json
mai 17 14:36:03 pc41.aws.edifixio.com org.gnome.Shell.desktop[1944]:   inflating: /home/fedora/.local/share/gnome-shell/extensions/focusli@feborg.es/sounds/database.json
mai 17 14:36:03 pc41.aws.edifixio.com org.gnome.Shell.desktop[1944]:   inflating: /home/fedora/.local/share/gnome-shell/extensions/focusli@feborg.es/extension.js
mai 17 14:36:03 pc41.aws.edifixio.com org.gnome.Shell.desktop[1944]:   inflating: /home/fedora/.local/share/gnome-shell/extensions/focusli@feborg.es/manager.js
mai 17 14:36:03 pc41.aws.edifixio.com org.gnome.Shell.desktop[1944]:   inflating: /home/fedora/.local/share/gnome-shell/extensions/focusli@feborg.es/stylesheet.css
mai 17 14:36:03 pc41.aws.edifixio.com org.gnome.Shell.desktop[1944]:   inflating: /home/fedora/.local/share/gnome-shell/extensions/focusli@feborg.es/sound.js

**Comment by felipeborges** [comment]
@roumano which version o gnome-shell do you have?

`$ gnome-shell --version`

**Comment by roumano** [comment]
Hi,

GNOME Shell 3.22.3 with a fedora 25 (with all package up2date)

**Comment by felipeborges** [comment]
@roumano I just submitted a new version of the extension compatible with 3.22.x. It is awaiting for approval.

Long story short, Gjs has changed in a way that you no longer need to define methods as
`myMethod: function(parameter) {`, so `myMethod() {` just works. We reintroduced the former syntax to be able to provide the compatibility with 3.22.

I hope it is going to work for you.

In the meantime, could you try to install it manually? To do so...
1. delete the folder from `~/.local/share/gnome-shell/extensions/focusli@feborg.es`
2. download it from https://github.com/felipeborges/gnome-shell-extension-focusli/archive/v0.2.zip
3. extract it as `~/.local/share/gnome-shell/extensions/focus@feborg.es` ?

**Comment by roumano** [comment]
Yes, it's better, it's now install successfully ( need to extract it on focusli@feborg.es not in focus@feborg.es )

with journalctl ( journalctl /usr/bin/gnome-shell -f -o cat ) , i now got this error (but the extension is loading ) : 
```
JS ERROR: Could not load extension gnome-shell-extension-focusli-0.2: Error: Missing metadata.json
```

I also see a  issue of Looping Sounds even after a gnome-shell restart  : 
- rain : sound for 19 seconds  then nothing
- wind, i only get it  7 seconds then nothing
- night : sound for 48 seconds then nothing
- lunch : sound for 16 seconds then nothing
- screen : sound for 5 seconds  then nothing
- cockroach: sound for 25 seconds then nothing

**Comment by felipeborges** [comment]
Oh, it was a typo, sorry. focusli it is. :)
Do you see the mp3 files in the sounds/ folder? The extension caches them after the first run so it doesn't waste your bandwidth.

**Comment by roumano** [comment]
Yes, i have them, 
somethime i got the sound for (rain 19secondes) then nothing for a couple of time (i will say 19secondes but not sure ) then the sound come back ...
```
tree sounds/
sounds/
├── Coffee_Shop.mp3
├── database.json
├── Fireplace.mp3
├── Rain.mp3
├── Summer_Night.mp3
├── White_Noise.mp3
└── Wind.mp3

0 directories, 7 files
```

**Comment by linksilver** [comment]
yeah go the same problem for installing, and now pauses between the song loop, same as #4 ?
btw it is a wonderfull app !
