### ISSUE TITLE
Proposal:  New focusli status icon

### ISSUE THREAD

**Issue by diazbastian** [armonge/gnome-shell-extension-focusli#9]
Focusli currently uses the same icon as RedShift, so I thought about doing some drawings for a new status icon. This will also help maintain consistency by using different custom icon packs.

![icon-proposal](https://cloud.githubusercontent.com/assets/5126124/26201131/728cdfda-3b9f-11e7-9daa-794837819353.png)

I was based on the metaphor of the sound wave, but the idea is that if there are more proposals join the discussion and of course, the author chooses.

[focusli-proposal-icon.zip](https://github.com/felipeborges/gnome-shell-extension-focusli/files/1010756/focusli-proposal-icon.zip)

**Comment by felipeborges** [comment]
@diazbastian wow! I love it.

Can you somehow specify, for the record, a licensing for these icons so I can include them on the extension?

**Comment by diazbastian** [comment]
@felipeborges I thought I had added in the SVG file metadata. [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) it's okay?

**Comment by felipeborges** [comment]
@diazbastian ops, I missed that. CC BY-SA 4.0 is great! Thanks!
